# try:
#     print("x")
# except:
#     print("an error occured")
# else:
#     print("no error")
# finally:
#     print("finished")        




# try:
#     print(x) 
# except NameError:
#     print("check wether x is defined")
# except:
#     print("error occured")    
    



# y=-5
# if y<0:
#     raise Exception("no number below zero is allowed")